### ISSUE TITLE
Some installation issues

### ISSUE THREAD

**Issue by quulah** [gofynd/ansible-metricbeat#3]
Installation for RedHat doesn't happen automatically. I added this as a workaround:
```
    - name: Install Metricbeat on RedHat
      become: yes
      include_role:
        name: gofynd.metricbeat
        tasks_from: redhat
      when: ansible_os_family == 'RedHat'
```

But a similar line to the one for [Debian](https://github.com/gofynd/ansible-metricbeat/blob/master/tasks/main.yml#L2) would be better.

And for Debian based systems, the package install doesn't obey `metricbeat_version`. [apt](https://github.com/gofynd/ansible-metricbeat/blob/master/tasks/debian.yml#L14) vs. [yum](https://github.com/gofynd/ansible-metricbeat/blob/master/tasks/redhat.yml#L16).
